# Generated by Django 5.1.3 on 2025-07-12 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RvsfRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gst_no', models.CharField(max_length=15, unique=True)),
                ('company_name', models.CharField(max_length=200)),
                ('legal_name', models.CharField(max_length=200)),
                ('company_email', models.EmailField(max_length=254)),
                ('business_category', models.CharField(max_length=100)),
                ('registered_address', models.TextField()),
                ('state', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=100)),
                ('pin_code', models.CharField(max_length=6)),
                ('website', models.URLField(blank=True, null=True)),
                ('company_pan', models.CharField(max_length=10)),
                ('tin_no', models.CharField(blank=True, max_length=50, null=True)),
                ('cin', models.CharField(blank=True, max_length=50, null=True)),
                ('iec', models.CharField(blank=True, max_length=50, null=True)),
                
            ],
        ),
    ]
