# Generated by Django 5.1.3 on 2025-07-12 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RvsfApp', '0002_remove_rvsfregistration_iec_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rvsfregistration',
            name='auth_email',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rvsfregistration',
            name='auth_mobile',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
