# Generated by Django 5.1.3 on 2025-07-14 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RvsfApp', '0005_rvsfregistration_iec'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('state', models.CharField(max_length=100)),
                ('cto_number', models.CharField(max_length=100)),
                ('consent_validity', models.DateField()),
                ('cto_pdf', models.FileField(upload_to='documents/RVSFDocs/Consent/')),
                ('howm_validity', models.DateField()),
                ('howm_pdf', models.FileField(upload_to='documents/RVSFDocs/Authorization/')),
                ('dic_validity', models.DateField()),
                ('dic_pdf', models.FileField(upload_to='documents/RVSFDocs/DICRegistration/')),
                ('rvsf_reg_no', models.CharField(max_length=100)),
                ('rvsf_validity', models.DateField()),
                ('rvsf_pdf', models.FileField(upload_to='documents/RVSFDocs/Rvsfpdf/')),
                ('process_flow_pdf', models.FileField(upload_to='documents/RVSFDocs/FlowDaigram/')),
                ('material_balance_pdf', models.FileField(upload_to='documents/RVSFDocs/MaterialBalance/')),
                ('annual_returns_pdf', models.FileField(upload_to='documents/RVSFDocs/AnnualReturns/')),
                ('userid', models.IntegerField(default=0, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
