# Generated by Django 5.1.3 on 2025-07-15 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RvsfApp', '0010_alter_equipmententry_equipment_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmententry',
            name='equipment_type',
            field=models.IntegerField(default=0),
        ),
    ]
