# Generated by Django 5.1.3 on 2025-07-15 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RvsfApp', '0012_equipmententry_equipment_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmententry',
            name='userid',
            field=models.IntegerField(default=0),
        ),
    ]
