# Generated by Django 5.1.3 on 2025-07-16 12:19

import RvsfApp.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RvsfApp', '0013_alter_equipmententry_userid'),
    ]

    operations = [
        migrations.CreateModel(
            name='RvsfFacility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('geo_video', models.FileField(upload_to='videos/geo_tagged/', validators=[RvsfApp.validators.validate_file_size])),
                ('total_area', models.DecimalField(decimal_places=2, max_digits=10)),
                ('shifts_per_day', models.IntegerField()),
                ('no_of_employees', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
