# Generated by Django 5.1.3 on 2025-07-18 12:10

import RvsfApp.models
import RvsfApp.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RvsfApp', '0014_rvsffacility'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, null=True, unique=True)),
                ('password', models.CharField(blank=True, max_length=128, null=True)),
                ('auth_mobile', models.CharField(default=9999999999, max_length=10)),
                ('auth_email', models.EmailField(default='test@gmail.com', max_length=254)),
                ('approval_doc', models.FileField(upload_to=RvsfApp.models.approval_doc, validators=[RvsfApp.validators.validate_file_size])),
                ('Status', models.IntegerField(default=0)),
            ],
        ),
        
    ]
