# Generated by Django 5.1.3 on 2025-07-18 12:28

import RvsfApp.models
import RvsfApp.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RvsfApp', '0015_profileapproval_alter_equipmententry_geo_tagged_pdf_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rvsfregistration',
            name='disable',
            field=models.IntegerField(default=0),
        ),
        
    ]
