# Generated by Django 5.1.3 on 2025-07-19 07:37

import RvsfApp.models
import RvsfApp.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RvsfApp', '0016_rvsfregistration_disable_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantCapacity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installed_vehicles', models.FloatField(default=0.0)),
                ('installed_steel', models.FloatField(default=0.0)),
                ('operating_vehicles1', models.FloatField(default=0.0)),
                ('operating_vehicles2', models.FloatField(default=0.0)),
                ('operating_vehicles3', models.FloatField(default=0.0)),
                ('operating_steel1', models.FloatField(default=0.0)),
                ('operating_steel2', models.FloatField(default=0.0)),
                ('operating_steel3', models.FloatField(default=0.0)),
                ('year1', models.CharField(max_length=50, null=True)),
                ('year2', models.CharField(max_length=50, null=True)),
                ('year3', models.CharField(max_length=50, null=True)),
                ('userid', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_type', models.CharField(max_length=200, null=True)),
                ('userid', models.IntegerField(default=0)),
                ('Remarks', models.TextField(null=True)),
            ],
        ),
       
    ]
