# Generated by Django 5.1.3 on 2025-07-21 11:07

import RvsfApp.models
import RvsfApp.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RvsfApp', '0018_pollutiondevice_wasterecycled_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfirmApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.IntegerField(default=0)),
                ('appno', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
       
    ]
