# Generated by Django 5.1.3 on 2025-07-27 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RvsfApp', '0022_alter_equipmententry_geo_tagged_pdf_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='confirmapplication',
            name='state_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='confirmapplication',
            name='statename',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
