# Generated by Django 5.1.3 on 2025-07-28 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RvsfApp', '0026_alter_confirmapplication_appstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='confirmapplication',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='confirmapplication',
            name='appstatus',
            field=models.IntegerField(choices=[(1, 'Submitted'), (2, 'Scrutiny'), (3, 'Inspection'), (4, 'Approved'), (5, 'Clarification Required'), (6, 'Response Received'), (7, 'Rejected')], default=1),
        ),
        migrations.AlterField(
            model_name='confirmapplication',
            name='transactionNo',
            field=models.CharField(default='1', max_length=100),
        ),
        migrations.AlterField(
            model_name='confirmapplication',
            name='userid',
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
