# Generated by Django 5.1.3 on 2025-08-05 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RvsfApp', '0027_confirmapplication_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='confirmapplication',
            name='EditPartA',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='confirmapplication',
            name='EditPartB',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='confirmapplication',
            name='EditPartC',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='confirmapplication',
            name='EditPartD',
            field=models.IntegerField(default=0),
        ),
    ]
