# Generated by Django 5.1.3 on 2025-08-06 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RvsfApp', '0029_rename_editparta_confirmapplication_incomplete_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='confirmapplication',
            name='incompleteRemark',
            field=models.TextField(null=True),
        ),
    ]
