# Generated by Django 5.1.3 on 2025-08-09 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RvsfApp', '0030_confirmapplication_incompleteremark'),
    ]

    operations = [
        migrations.AddField(
            model_name='confirmapplication',
            name='IndustryRemark',
            field=models.TextField(null=True),
        ),
    ]
