# Generated by Django 5.1.3 on 2025-08-09 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RvsfApp', '0031_confirmapplication_industryremark'),
    ]

    operations = [
        migrations.AddField(
            model_name='confirmapplication',
            name='response',
            field=models.IntegerField(default=0),
        ),
    ]
