# Generated by Django 5.1.2 on 2025-08-21 07:07

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RvsfApp', '0032_confirmapplication_response'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=30, unique=True)),
                ('txn_id', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('amount_initiated', models.IntegerField()),
                ('was_success', models.BooleanField(default=False)),
                ('status', models.CharField(blank=True, max_length=30, null=True)),
                ('log', models.TextField(blank=True, null=True)),
                ('registered_for', models.TextField(blank=True, null=True)),
                ('txn_date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('ru_date', models.DateTimeField(blank=True, null=True)),
                ('s2s_date', models.DateTimeField(blank=True, null=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='RvsfApp.rvsfregistration')),
            ],
        ),
    ]
