# Generated by Django 5.1.2 on 2025-08-21 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RvsfApp', '0033_transaction'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Transaction',
            new_name='Payment',
        ),
    ]
