# Generated by Django 5.2.6 on 2025-10-27 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RvsfApp', '0036_generaldetails_cin_pdf_generaldetails_gst_pdf_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rvsfregistration',
            name='completed_step',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='rvsfregistration',
            name='first_login',
            field=models.IntegerField(default=0),
        ),
    ]
