# Generated by Django 5.2.6 on 2025-10-27 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RvsfApp', '0037_rvsfregistration_completed_step_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rvsfregistration',
            name='authorized_person_name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
