# Generated by Django 5.2.6 on 2025-10-28 05:12

import RvsfApp.models
import RvsfApp.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RvsfApp', '0038_rvsfregistration_authorized_person_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='RvsfDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('state', models.CharField(default='NA', max_length=100)),
                ('district', models.CharField(default='NA', max_length=100)),
                ('pin_code', models.CharField(default='NA', max_length=20)),
                ('cto_number', models.CharField(max_length=100)),
                ('consent_validity', models.DateField()),
                ('cto_pdf', models.FileField(upload_to=RvsfApp.models.consent_upload_path, validators=[RvsfApp.validators.validate_file_size])),
                ('howm_validity', models.DateField()),
                ('howm_pdf', models.FileField(upload_to=RvsfApp.models.authorization_upload_path, validators=[RvsfApp.validators.validate_file_size])),
                ('dic_validity', models.DateField()),
                ('dic_pdf', models.FileField(upload_to=RvsfApp.models.dic_upload_path, validators=[RvsfApp.validators.validate_file_size])),
                ('rvsf_reg_no', models.CharField(max_length=100)),
                ('rvsf_validity', models.DateField()),
                ('rvsf_pdf', models.FileField(upload_to=RvsfApp.models.rvsf_upload_path, validators=[RvsfApp.validators.validate_file_size])),
                ('process_flow_pdf', models.FileField(upload_to=RvsfApp.models.flow_diagram_upload_path, validators=[RvsfApp.validators.validate_file_size])),
                ('material_balance_pdf', models.FileField(upload_to=RvsfApp.models.material_balance_upload_path, validators=[RvsfApp.validators.validate_file_size])),
                ('annual_returns_pdf', models.FileField(upload_to=RvsfApp.models.annual_return_upload_path, validators=[RvsfApp.validators.validate_file_size])),
                ('tin_pdf', models.FileField(blank=True, upload_to=RvsfApp.models.TinDoc, validators=[RvsfApp.validators.validate_file_size])),
                ('pan_pdf', models.FileField(blank=True, upload_to=RvsfApp.models.PanDoc, validators=[RvsfApp.validators.validate_file_size])),
                ('cin_pdf', models.FileField(blank=True, upload_to=RvsfApp.models.CinDoc, validators=[RvsfApp.validators.validate_file_size])),
                ('gst_pdf', models.FileField(blank=True, upload_to=RvsfApp.models.GstDoc, validators=[RvsfApp.validators.validate_file_size])),
                ('iec_pdf', models.FileField(blank=True, upload_to=RvsfApp.models.IecDoc, validators=[RvsfApp.validators.validate_file_size])),
                ('userid', models.IntegerField(default=0, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
