# Generated by Django 5.2.6 on 2025-10-29 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RvsfApp', '0041_rvsfregistration_password_history_activesession'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmententry',
            name='capacity_equipment_perton',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='equipmententry',
            name='operating_hours',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='equipmententry',
            name='power_rating',
            field=models.IntegerField(default=0),
        ),
    ]
