# Generated by Django 5.2.6 on 2025-11-12 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RvsfApp', '0046_rvsfregistration_designation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rvsfregistration',
            old_name='designation',
            new_name='auth_designation',
        ),
    ]
