# Generated by Django 5.2.6 on 2025-11-19 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RvsfApp', '0047_rename_designation_rvsfregistration_auth_designation'),
    ]

    operations = [
        migrations.AddField(
            model_name='confirmapplication',
            name='marked_by_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='confirmapplication',
            name='marked_to_id',
            field=models.IntegerField(default=0),
        ),
    ]
