# Generated by Django 5.2.6 on 2025-11-27 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RvsfApp', '0051_alter_payment_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='payment',
            table=None,
        ),
    ]
