# Generated by Django 5.2.6 on 2025-12-29 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RvsfApp', '0056_rvsfdetails_encorp_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmententry',
            name='equipment_description',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
