# Generated by Django 5.2.6 on 2026-01-02 10:35

import RvsfApp.models
import RvsfApp.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RvsfApp', '0057_equipmententry_equipment_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='rvsfdetails',
            name='annual_returns_pdf2',
            field=models.FileField(default='', upload_to=RvsfApp.models.annual_return_upload_path2, validators=[RvsfApp.validators.validate_file_size]),
            preserve_default=False,
        ),
    ]
