# Generated by Django 5.2.6 on 2026-01-16 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RvsfApp', '0060_rvsfregistration_attested_certificate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='confirmapplication',
            name='certificateno',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
