# Generated by Django 5.2.6 on 2026-02-26 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RvsfApp', '0062_rvsfdetails_unit_commencement_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='rvsfdetails',
            name='gpcbid',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
