# Generated by Django 5.2.6 on 2026-04-30 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RvsfApp', '0064_alter_equipmententry_equipment_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='confirmapplication',
            name='certificateattested',
            field=models.IntegerField(default=0),
        ),
    ]
