# Generated by Django 5.2.6 on 2025-11-11 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("registration", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CpcbUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=150, unique=True)),
                ("password", models.CharField(max_length=128)),
                ("first_name", models.CharField(blank=True, max_length=150)),
                ("last_name", models.CharField(blank=True, max_length=150)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("mobile_no", models.CharField(blank=True, default="", max_length=20)),
                ("division", models.CharField(blank=True, default="", max_length=100)),
                ("is_active", models.BooleanField(default=True)),
                ("first_login", models.IntegerField(default=0)),
                ("password_history", models.TextField(default="[]")),
            ],
            options={
                "db_table": "CpcbApp_user",
            },
        ),
        migrations.CreateModel(
            name="ProgressStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
            options={
                "db_table": "CpcbApp_progressstatus",
            },
        ),
        migrations.CreateModel(
            name="RoleType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
            options={
                "db_table": "CpcbApp_roletype",
            },
        ),
        migrations.CreateModel(
            name="CertificateRegistry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("registration_no", models.CharField(max_length=20, unique=True)),
                ("issued_at", models.DateTimeField(auto_now_add=True)),
                (
                    "producer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="registration.producergeneraldetails",
                    ),
                ),
            ],
            options={
                "db_table": "CpcbApp_certificateregistry",
            },
        ),
        migrations.CreateModel(
            name="Checklist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "producer_name_address",
                    models.CharField(
                        blank=True,
                        choices=[("yes", "Yes"), ("no", "No")],
                        max_length=3,
                        null=True,
                    ),
                ),
                (
                    "remarks_producer_name_address",
                    models.TextField(blank=True, null=True),
                ),
                (
                    "company_email",
                    models.CharField(
                        blank=True,
                        choices=[("yes", "Yes"), ("no", "No")],
                        max_length=3,
                        null=True,
                    ),
                ),
                ("remarks_company_email", models.TextField(blank=True, null=True)),
                (
                    "upload_gst_certificate",
                    models.CharField(
                        blank=True,
                        choices=[("yes", "Yes"), ("no", "No")],
                        max_length=3,
                        null=True,
                    ),
                ),
                (
                    "remarks_upload_gst_certificate",
                    models.TextField(blank=True, null=True),
                ),
                (
                    "year_of_incorporation",
                    models.CharField(
                        blank=True,
                        choices=[("yes", "Yes"), ("no", "No")],
                        max_length=3,
                        null=True,
                    ),
                ),
                (
                    "remarks_year_of_incorporation",
                    models.TextField(blank=True, null=True),
                ),
                (
                    "pan_card_uploaded",
                    models.CharField(
                        blank=True,
                        choices=[("yes", "Yes"), ("no", "No")],
                        max_length=3,
                        null=True,
                    ),
                ),
                ("remarks_pan_card_uploaded", models.TextField(blank=True, null=True)),
                (
                    "tin_certificate_uploaded",
                    models.CharField(
                        blank=True,
                        choices=[("yes", "Yes"), ("no", "No")],
                        max_length=3,
                        null=True,
                    ),
                ),
                (
                    "remarks_tin_certificate_uploaded",
                    models.TextField(blank=True, null=True),
                ),
                (
                    "cin_certificate_uploaded",
                    models.CharField(
                        blank=True,
                        choices=[("yes", "Yes"), ("no", "No")],
                        max_length=3,
                        null=True,
                    ),
                ),
                (
                    "remarks_cin_certificate_uploaded",
                    models.TextField(blank=True, null=True),
                ),
                (
                    "iec_certificate_uploaded",
                    models.CharField(
                        blank=True,
                        choices=[("yes", "Yes"), ("no", "No")],
                        max_length=3,
                        null=True,
                    ),
                ),
                (
                    "remarks_iec_certificate_uploaded",
                    models.TextField(blank=True, null=True),
                ),
                (
                    "authorized_person_details",
                    models.CharField(
                        blank=True,
                        choices=[("yes", "Yes"), ("no", "No")],
                        max_length=3,
                        null=True,
                    ),
                ),
                (
                    "authorized_person_pan_details",
                    models.CharField(
                        blank=True,
                        choices=[("yes", "Yes"), ("no", "No")],
                        max_length=3,
                        null=True,
                    ),
                ),
                (
                    "remarks_authorized_person_details",
                    models.TextField(blank=True, null=True),
                ),
                (
                    "nature_of_business",
                    models.CharField(
                        blank=True,
                        choices=[("yes", "Yes"), ("no", "No")],
                        max_length=3,
                        null=True,
                    ),
                ),
                ("remarks_nature_of_business", models.TextField(blank=True, null=True)),
                (
                    "name_address_facility",
                    models.CharField(
                        blank=True,
                        choices=[("yes", "Yes"), ("no", "No")],
                        max_length=3,
                        null=True,
                    ),
                ),
                (
                    "remarks_name_address_facility",
                    models.TextField(blank=True, null=True),
                ),
                (
                    "activity_type",
                    models.CharField(
                        blank=True,
                        choices=[("yes", "Yes"), ("no", "No")],
                        max_length=3,
                        null=True,
                    ),
                ),
                ("remarks_activity_type", models.TextField(blank=True, null=True)),
                (
                    "capacity_of_facility",
                    models.CharField(
                        blank=True,
                        choices=[("yes", "Yes"), ("no", "No")],
                        max_length=3,
                        null=True,
                    ),
                ),
                (
                    "remarks_capacity_of_facility",
                    models.TextField(blank=True, null=True),
                ),
                (
                    "data_transport",
                    models.CharField(
                        blank=True,
                        choices=[("yes", "Yes"), ("no", "No")],
                        max_length=3,
                        null=True,
                    ),
                ),
                ("remarks_data_transport", models.TextField(blank=True, null=True)),
                (
                    "fy_data_transport",
                    models.CharField(
                        blank=True,
                        choices=[("yes", "Yes"), ("no", "No")],
                        max_length=3,
                        null=True,
                    ),
                ),
                ("remarks_fy_data_transport", models.TextField(blank=True, null=True)),
                (
                    "vehicle_data_transport",
                    models.CharField(
                        blank=True,
                        choices=[("yes", "Yes"), ("no", "No")],
                        max_length=3,
                        null=True,
                    ),
                ),
                (
                    "remarks_vehicle_data_transport",
                    models.TextField(blank=True, null=True),
                ),
                (
                    "manufactured_data_transport",
                    models.CharField(
                        blank=True,
                        choices=[("yes", "Yes"), ("no", "No")],
                        max_length=3,
                        null=True,
                    ),
                ),
                (
                    "remarks_manufactured_data_transport",
                    models.TextField(blank=True, null=True),
                ),
                (
                    "open_market_sales_data_transport",
                    models.CharField(
                        blank=True,
                        choices=[("yes", "Yes"), ("no", "No")],
                        max_length=3,
                        null=True,
                    ),
                ),
                (
                    "remarks_open_market_sales_data_transport",
                    models.TextField(blank=True, null=True),
                ),
                (
                    "other_producer_sales_data_transport",
                    models.CharField(
                        blank=True,
                        choices=[("yes", "Yes"), ("no", "No")],
                        max_length=3,
                        null=True,
                    ),
                ),
                (
                    "remarks_other_producer_sales_data_transport",
                    models.TextField(blank=True, null=True),
                ),
                (
                    "cobranding_sales_data_transport",
                    models.CharField(
                        blank=True,
                        choices=[("yes", "Yes"), ("no", "No")],
                        max_length=3,
                        null=True,
                    ),
                ),
                (
                    "remarks_cobranding_sales_data_transport",
                    models.TextField(blank=True, null=True),
                ),
                (
                    "uploaded_excel_other_producer_standard_format_transport",
                    models.CharField(
                        blank=True,
                        choices=[("yes", "Yes"), ("no", "No")],
                        max_length=3,
                        null=True,
                    ),
                ),
                (
                    "remarks_uploaded_excel_other_producer_standard_format_transport",
                    models.TextField(blank=True, null=True),
                ),
                (
                    "self_use_transport",
                    models.CharField(
                        blank=True,
                        choices=[("yes", "Yes"), ("no", "No")],
                        max_length=3,
                        null=True,
                    ),
                ),
                ("remarks_self_use_transport", models.TextField(blank=True, null=True)),
                (
                    "exported_vehicles_transport",
                    models.CharField(
                        blank=True,
                        choices=[("yes", "Yes"), ("no", "No")],
                        max_length=3,
                        null=True,
                    ),
                ),
                (
                    "remarks_exported_vehicles_transport",
                    models.TextField(blank=True, null=True),
                ),
                (
                    "uploaded_ca_certificates_each_fy_transport",
                    models.CharField(
                        blank=True,
                        choices=[("yes", "Yes"), ("no", "No")],
                        max_length=3,
                        null=True,
                    ),
                ),
                (
                    "remarks_uploaded_ca_certificates_each_fy_transport",
                    models.TextField(blank=True, null=True),
                ),
                (
                    "data_non_transport",
                    models.CharField(
                        blank=True,
                        choices=[("yes", "Yes"), ("no", "No")],
                        max_length=3,
                        null=True,
                    ),
                ),
                ("remarks_data_non_transport", models.TextField(blank=True, null=True)),
                (
                    "fy_data_non_transport",
                    models.CharField(
                        blank=True,
                        choices=[("yes", "Yes"), ("no", "No")],
                        max_length=3,
                        null=True,
                    ),
                ),
                (
                    "remarks_fy_data_non_transport",
                    models.TextField(blank=True, null=True),
                ),
                (
                    "vehicle_data_non_transport",
                    models.CharField(
                        blank=True,
                        choices=[("yes", "Yes"), ("no", "No")],
                        max_length=3,
                        null=True,
                    ),
                ),
                (
                    "remarks_vehicle_data_non_transport",
                    models.TextField(blank=True, null=True),
                ),
                (
                    "manufactured_data_non_transport",
                    models.CharField(
                        blank=True,
                        choices=[("yes", "Yes"), ("no", "No")],
                        max_length=3,
                        null=True,
                    ),
                ),
                (
                    "remarks_manufactured_data_non_transport",
                    models.TextField(blank=True, null=True),
                ),
                (
                    "open_market_sales_data_non_transport",
                    models.CharField(
                        blank=True,
                        choices=[("yes", "Yes"), ("no", "No")],
                        max_length=3,
                        null=True,
                    ),
                ),
                (
                    "remarks_open_market_sales_data_non_transport",
                    models.TextField(blank=True, null=True),
                ),
                (
                    "other_producer_sales_data_non_transport",
                    models.CharField(
                        blank=True,
                        choices=[("yes", "Yes"), ("no", "No")],
                        max_length=3,
                        null=True,
                    ),
                ),
                (
                    "remarks_other_producer_sales_data_non_transport",
                    models.TextField(blank=True, null=True),
                ),
                (
                    "cobranding_sales_data_non_transport",
                    models.CharField(
                        blank=True,
                        choices=[("yes", "Yes"), ("no", "No")],
                        max_length=3,
                        null=True,
                    ),
                ),
                (
                    "remarks_cobranding_sales_data_non_transport",
                    models.TextField(blank=True, null=True),
                ),
                (
                    "uploaded_excel_standard_format_non_transport",
                    models.CharField(
                        blank=True,
                        choices=[("yes", "Yes"), ("no", "No")],
                        max_length=3,
                        null=True,
                    ),
                ),
                (
                    "remarks_uploaded_excel_standard_format_non_transport",
                    models.TextField(blank=True, null=True),
                ),
                (
                    "self_use_non_transport",
                    models.CharField(
                        blank=True,
                        choices=[("yes", "Yes"), ("no", "No")],
                        max_length=3,
                        null=True,
                    ),
                ),
                (
                    "remarks_self_use_non_transport",
                    models.TextField(blank=True, null=True),
                ),
                (
                    "exported_vehicles_non_transport",
                    models.CharField(
                        blank=True,
                        choices=[("yes", "Yes"), ("no", "No")],
                        max_length=3,
                        null=True,
                    ),
                ),
                (
                    "remarks_exported_vehicles_non_transport",
                    models.TextField(blank=True, null=True),
                ),
                (
                    "uploaded_ca_certificates_each_fy_non_transport",
                    models.CharField(
                        blank=True,
                        choices=[("yes", "Yes"), ("no", "No")],
                        max_length=3,
                        null=True,
                    ),
                ),
                (
                    "remarks_uploaded_ca_certificates_each_fy_non_transport",
                    models.TextField(blank=True, null=True),
                ),
                (
                    "provided_annual_turnover_both_fy",
                    models.CharField(
                        blank=True,
                        choices=[("yes", "Yes"), ("no", "No")],
                        max_length=3,
                        null=True,
                    ),
                ),
                (
                    "remarks_provided_annual_turnover_both_fy",
                    models.TextField(blank=True, null=True),
                ),
                (
                    "uploaded_ca_certificate_each_fy",
                    models.CharField(
                        blank=True,
                        choices=[("yes", "Yes"), ("no", "No")],
                        max_length=3,
                        null=True,
                    ),
                ),
                (
                    "remarks_uploaded_ca_certificate_each_fy",
                    models.TextField(blank=True, null=True),
                ),
                (
                    "uploaded_undertaking",
                    models.CharField(
                        blank=True,
                        choices=[("yes", "Yes"), ("no", "No")],
                        max_length=3,
                        null=True,
                    ),
                ),
                (
                    "remarks_uploaded_undertaking",
                    models.TextField(blank=True, null=True),
                ),
                (
                    "reg_fee",
                    models.CharField(
                        blank=True,
                        choices=[("yes", "Yes"), ("no", "No")],
                        max_length=3,
                        null=True,
                    ),
                ),
                ("remarks_reg_fee", models.TextField(blank=True, null=True)),
                (
                    "producer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="checklist",
                        to="registration.producergeneraldetails",
                    ),
                ),
            ],
            options={
                "db_table": "CpcbApp_checklist",
            },
        ),
        migrations.CreateModel(
            name="Noting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("comment", models.TextField()),
                ("last_updated_by", models.IntegerField()),
                ("forwarded_from", models.IntegerField()),
                ("forwarded_to", models.IntegerField()),
                ("forwarded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "checklist",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="noting_checklist",
                        to="CpcbApp.checklist",
                    ),
                ),
                (
                    "producer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="noting",
                        to="registration.producergeneraldetails",
                    ),
                ),
            ],
            options={
                "db_table": "CpcbApp_noting",
            },
        ),
    ]
