# Generated by Django 5.2.6 on 2025-11-12 05:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CpcbApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cpcbuser',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='cpcbuser',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
