# Generated by Django 5.2.6 on 2025-11-12 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CpcbApp', '0002_cpcbuser_date_joined_cpcbuser_last_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='cpcbuser',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
