# Generated by Django 5.2.6 on 2025-11-18 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CpcbApp', '0003_cpcbuser_is_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklist',
            name='remarks_authorized_person_pan_details',
            field=models.TextField(blank=True, null=True),
        ),
    ]
