# Generated by Django 5.2.6 on 2025-12-05 10:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CpcbApp', '0004_checklist_remarks_authorized_person_pan_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noting',
            name='forwarded_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
