"""
Django settings for ELV project.

Generated by 'django-admin startproject' using Django 5.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os
import pdfkit
import platform

CRYPTOGRAPHY_ENCRYPTION_KEY = b"HsCih6RKKPZlY55SECelx0lv3ahuPi3lERT_WI9ErqE="

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
TEMPLATE_DIR = str(BASE_DIR / "registration" / "templates")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-xj!ebnm6qy7x5bf7wl0f(ls@=px3n*u@acbusd@2u=_#7_uenw'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    # 'registration',
    'registration.apps.RegistrationConfig',
    'CpcbApp',
    'bulk_consumer',
    'RvsfApp',
    'SpcbApp',
    'captcha',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'registration.middleware.AutoLogout',
    'registration.middleware.NoCacheMiddleware',
    'registration.middleware.RemoveServerHeadersMiddleware',
    "registration.middleware.OneSessionPerUserMiddleware",
    'registration.middleware.MetadataStripMiddleware',
]

# ✅ Ensure sessions are stored in the database (not lost)
SESSION_ENGINE = 'django.contrib.sessions.backends.db'

CSRF_TRUSTED_ORIGINS = ["https://demosignergateway.emsigner.com/"]

ROOT_URLCONF = 'ELV.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [TEMPLATE_DIR],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'ELV.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases


# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.mysql',
#         'NAME': 'elv_new',
#         'USER':'root',
#         'PASSWORD':'',
#         'HOST':'localhost',
#         'PORT':'3307',
#         'OPTIONS': {
#             'sql_mode': 'STRICT_TRANS_TABLES',
#         },
#     }
# }


# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.mysql',
#         'NAME': 'elv_08-07-2025',
#         'USER':'root',
#         'PASSWORD':'root',
#         'HOST':'localhost',
#         'PORT':'8889',
#         'OPTIONS': {
#             'sql_mode': 'STRICT_TRANS_TABLES',
#         },
#     }
# }


# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.mysql',
#         'NAME': 'elv_latest_23_06_2025',
#         'USER':'cpcbelv',
#         'PASSWORD':'ELVj3uD@cpcb',
#         'HOST':'localhost',
#         'PORT':'3306',
#         'OPTIONS': {
#             'sql_mode': 'STRICT_TRANS_TABLES',
#         },
#     }
# }

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'elv_new',
        'USER':'cpcbelv',
        'PASSWORD':'ELVj3uD@cpcb',
        'HOST':'10.24.84.232',
        'PORT':'3306',
        'OPTIONS': {
            'sql_mode': 'STRICT_TRANS_TABLES',
        },
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

# Implement Redis for cache management

CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": "redis://127.0.0.1:6379/1",
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient"
        }
        
    }
}


AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = '/static/'
# STATIC_URL = '/68a40044-6090-8321-8491-20de09365a28/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
 
MEDIA_URL = '/media/'
# MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_ROOT = '/opt/ELV/documents/'
# Media access control rules
# settings.py - RECOMMENDED CONFIG
MEDIA_ACCESS_RULES = {
    'ALLOWED_DIRECTORIES': [
        # Be VERY specific about what's allowed
        'documents/public/',
        'images/avatars/',
        'uploads/temp/',
    ],
    
    'BLOCKED_DIRECTORIES': [
        # Block everything else by default
        'documents/',  # This blocks ALL documents except the specific allowed ones above
        'images/',
        'uploads/',
        'private/',
        'secret/',
        'config/',
        'documents/auth_person_pan/',  # Specifically block this folder
    ],
    
    'ALLOWED_EXTENSIONS': [
        '.pdf', '.jpg', '.jpeg', '.png', '.gif',
        '.doc', '.docx', '.txt', '.csv'
    ],
    
    'BLOCKED_EXTENSIONS': [
        '.exe', '.php', '.sh', '.bat', '.py', '.js',
        '.html', '.htm', '.css', '.sql', '.env'
    ],
    
    'REQUIRE_AUTHENTICATION': [
        'documents/auth_person_pan/',  # Or require login for this folder
        'private/',
        'user_uploads/',
    ]
}

SESSION_COOKIE_PATH = '/'
CSRF_COOKIE_PATH = '/'

RATELIMIT_IP_META_KEY = 'HTTP_X_FORWARDED_FOR'

# SESSION_COOKIE_PATH = '/admin'
# CSRF_COOKIE_PATH = '/admin'

# # SPCB module
# SESSION_COOKIE_PATH = '/spcb'
# CSRF_COOKIE_PATH = '/spcb'

# # Producer module
# SESSION_COOKIE_PATH = '/producer'
# CSRF_COOKIE_PATH = '/producer'

# # RVSF module
# SESSION_COOKIE_PATH = '/rvsf'
# CSRF_COOKIE_PATH = '/rvsf'


# CAPTCHA_IMAGE_SIZE = (175, 50)  # Set the width and height of the CAPTCHA image
# CAPTCHA_LENGTH = 6  # Increase the number of characters in the CAPTCHA (default is 4)
# CAPTCHA_FONT_SIZE = 30  # Set the font size for the CAPTCHA text
# # CAPTCHA_FONT_PATH = "/path/to/font.ttf"  # Provide a specific path to a .ttf font file
# CAPTCHA_NOISE_FUNCTIONS = ('captcha.helpers.noise_arcs', 'captcha.helpers.noise_dots')
# CAPTCHA_BACKGROUND_COLOR = "#f0f2f5"  # Background color
# CAPTCHA_FOREGROUND_COLOR = "#020f2c"  # Text color
# CAPTCHA_CHALLENGE_FUNCT = 'captcha.helpers.random_char_challenge'  # Mix of letters and numbers
# CAPTCHA_TIMEOUT = 5  # Timeout for CAPTCHA in minutes (default is 5)
# CAPTCHA_FONT_PATH = None  # Use default font or specify a path to a .ttf file


CAPTCHA_IMAGE_SIZE = (175, 50)  # Set the width and height of the CAPTCHA image
CAPTCHA_LENGTH = 6  # Increase the number of characters in the CAPTCHA (default is 4)
CAPTCHA_FONT_SIZE = 30  # Set the font size for the CAPTCHA text
# CAPTCHA_FONT_PATH = "/path/to/font.ttf"  # Provide a specific path to a .ttf font file
CAPTCHA_NOISE_FUNCTIONS = ('captcha.helpers.noise_arcs', 'captcha.helpers.noise_dots')
CAPTCHA_BACKGROUND_COLOR = "#f0f2f5"  # Background color
CAPTCHA_FOREGROUND_COLOR = "#020f2c"  # Text color
# CAPTCHA_CHALLENGE_FUNCT = 'captcha.helpers.random_char_challenge'  # Mix of letters and numbers
CAPTCHA_CHALLENGE_FUNCT = 'registration.captcha_challenges.complex_symbol_challenge'

CAPTCHA_TIMEOUT = 5  # Timeout for CAPTCHA in minutes (default is 5)
# CAPTCHA_FONT_PATH = None  # Use default font or specify a path to a .ttf file

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field



# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_HOST = 'smtp.gmail.com'  # Change if using another provider
# EMAIL_PORT = 587
# EMAIL_USE_TLS = True
# EMAIL_HOST_USER = 'help.cpcb@gmail.com'  # Your email
# EMAIL_HOST_PASSWORD = 'qqogaurtygbeakdi'  # App password or actual password
# DEFAULT_FROM_EMAIL = EMAIL_HOST_USER

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'  # Change if using another provider
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'hwmd.cpcb@gmail.com'  # Your email
EMAIL_HOST_PASSWORD = "sntyeregrawgzrue"
# EMAIL_HOST_USER = 'test.consent.cpcb@gmail.com'  # Your email
# EMAIL_HOST_PASSWORD = 'lvznpwmaaiqhtqdg'  # App password or actual password:
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER


# SMS
# TWILIO_SID = 'ACc2434ce19dd33de8bfe4ac5413d1f234'
# TWILIO_AUTH_TOKEN = 'da97df03da87317c75e08d516ac3995a'
# TWILIO_PHONE_NUMBER = '+18483152997'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
# AUTH_USER_MODEL = 'registration.User'

# MEDIA_URL = '/documents/'
# MEDIA_ROOT = BASE_DIR / 'documents'




# settings.py

BILLDESK_MERCHANT_ID = 'XBIHARGRAS'
BILLDESK_CLIENT_ID = 'xbihargras'       # UAT

BILLDESK_KEY_ID = '7VYad7hnhet13jXvxCFoFAvpAwTqH60I'  # <-- This is your Authorization key // Production

BILLDESK_ENCRYPTION_KEY = 'zvSpVgG0hZO5pCcpjM0Em48IauHP8mqL'
BILLDESK_SIGNING_KEY = '21eWrxFIcloCBXOPKf65iscLd8PPKLMP'
BILLDESK_API_ENDPOINT = 'https://uat1.billdesk.com/u2/payments/ve1_2/orders/create'     # UAT

# BILLDESK_MERCHANT_ID = 'XBCEFCPELV'   # Production
# BILLDESK_CLIENT_ID = 'xbcefcpelv'    # Production
# BILLDESK_KEY_ID = 'hv5hosPFNY4nx6URKMG1d0ctwxUROIKw'  # Production
# BILLDESK_API_ENDPOINT = 'https://api.billdesk.com/payments/ve1_2/ecomorders/create'    #Production

# WKHTMLTOPDF_CMD = "/usr/local/bin/wkhtmltopdf"

if platform.system() == "Windows":
    # Path for Windows
    WKHTMLTOPDF_CMD = r"C:\Program Files\wkhtmltopdf\bin\wkhtmltopdf.exe"
else:
    # Path for Linux (binary installed via apt or wget)
    WKHTMLTOPDF_CMD = "/usr/local/bin/wkhtmltopdf"

# Ensure file exists
if not os.path.exists(WKHTMLTOPDF_CMD):
    # Fallback for systems where wkhtmltopdf is in PATH
    WKHTMLTOPDF_CMD = "wkhtmltopdf"

PDFKIT_CONFIG = pdfkit.configuration(wkhtmltopdf=WKHTMLTOPDF_CMD)


ESIGNER_AUTHTOKEN = "33b71185-f46d-4fcd-b8ed-fafb6644e31c" # Replace in prod


# Set session to expire in 30 minutes (1800 seconds)
# SESSION_COOKIE_AGE = 1800  # 30 minutes

# Optional: Ensure the session is deleted when the browser is closed
# SESSION_EXPIRE_AT_BROWSER_CLOSE = True

LOGGING ={
    'version':1,
    'loggers':{
        'django':{
            'handlers':['console'],
            'level':'DEBUG',
        }
        },
    'handlers':{
        'console':{
            'level':'INFO',
            'class':'logging.StreamHandler',
            'formatter':'simpleRe',
        }
        },
    'formatters':{
        'simpleRe':{
            'format':'{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style':'{',
            
        }
    }
}


import warnings

warnings.filterwarnings(
    'ignore',
    message='Model .* was already registered',
    category=RuntimeWarning,
)


# Load additional security settings only in production
if not DEBUG:
    try:
        from .settings_security_dev import *
    except ImportError:
        # Optional safeguard: log a warning instead of breaking
        import warnings
        warnings.warn("settings_security.py not found! Security settings are not applied.")
else:
    try:
        from .settings_security_dev import *
    except ImportError:
        # Optional safeguard: log a warning instead of breaking
        import warnings
        warnings.warn("settings_security.py not found! Security settings are not applied.")

SESSION_COOKIE_AGE = 30 * 60  # 30 min
SESSION_SAVE_EVERY_REQUEST = True
SESSION_EXPIRE_AT_BROWSER_CLOSE = True

# Custom auto logout settings
SESSION_EXPIRE_SECONDS = 1800
SESSION_EXPIRE_AFTER_LAST_ACTIVITY = True
SESSION_TIMEOUT_REDIRECT = "/login/"
LOGIN_URL = "/login/"
