# Generated by Django 5.2.6 on 2025-11-11 12:42

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ManufacturingDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nature_of_business", models.CharField(max_length=255)),
                (
                    "has_facility",
                    models.CharField(
                        choices=[("Yes", "Yes"), ("No", "No")],
                        default="No",
                        max_length=3,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="OTP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("company_email", "Company Email"),
                            ("authorized_person_email", "Authorized Person Email"),
                            ("authorized_person_mobile", "Authorized Person Mobile"),
                        ],
                        max_length=30,
                    ),
                ),
                ("authorization", models.CharField(max_length=255)),
                ("otp", models.CharField(blank=True, max_length=6, null=True)),
                ("otp_verified", models.BooleanField(default=False)),
                ("otp_expires_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="producerGeneralDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("gst_no", models.CharField(max_length=15, unique=True)),
                ("gst_doc", models.FileField(upload_to="documents/gst/")),
                ("company_name", models.CharField(max_length=255)),
                ("legal_name", models.CharField(max_length=255)),
                ("company_email", models.EmailField(max_length=254)),
                ("incorporation_date", models.IntegerField()),
                ("business_category", models.CharField(max_length=255)),
                ("registered_address", models.TextField()),
                ("state", models.CharField(max_length=100)),
                ("district", models.CharField(max_length=100)),
                ("pin_code", models.CharField(max_length=10)),
                ("website", models.URLField(blank=True, null=True)),
                ("pan_no", models.CharField(max_length=10)),
                ("pan_doc", models.FileField(upload_to="documents/company_pan/")),
                ("tin", models.CharField(blank=True, max_length=20, null=True)),
                ("tin_doc", models.FileField(upload_to="documents/tin/")),
                ("cin", models.CharField(blank=True, max_length=21, null=True)),
                ("cin_doc", models.FileField(upload_to="documents/cin/")),
                ("iec", models.CharField(blank=True, max_length=20, null=True)),
                ("iec_doc", models.FileField(upload_to="documents/iec/")),
                ("authorized_person_name", models.CharField(max_length=255)),
                ("authorized_person_designation", models.CharField(max_length=255)),
                ("authorized_person_email", models.EmailField(max_length=254)),
                ("authorized_person_mobile", models.CharField(max_length=15)),
                ("authorized_person_pan", models.CharField(max_length=10)),
                ("doc", models.FileField(upload_to="documents/auth_person_pan")),
                ("user_type", models.CharField(max_length=10)),
                ("status", models.IntegerField(default=0)),
                ("forwarded_to", models.IntegerField(default=0)),
                ("application_type", models.IntegerField(default=0)),
                ("application_submitted", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="ProducerRegistrationFee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "min_turnover",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "max_turnover",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                ("registration_fee", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Registration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("entity_types", models.CharField(blank=True, max_length=10)),
                ("gst_no", models.CharField(blank=True, max_length=15, unique=True)),
                ("company_name", models.CharField(blank=True, max_length=200)),
                ("legal_name", models.CharField(blank=True, max_length=200)),
                ("company_email", models.EmailField(blank=True, max_length=254)),
                (
                    "business_category",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Government Agency", "Government Agency"),
                            (
                                "Government-Owned Enterprise (Govt. / PSU)",
                                "Government-Owned Enterprise (Govt. / PSU)",
                            ),
                            (
                                "Private Limited Company (Ltd.)",
                                "Private Limited Company (Ltd.)",
                            ),
                            (
                                "Proprietorship/Partnership Firm",
                                "Proprietorship/Partnership Firm",
                            ),
                            (
                                "Limited Liability Partnership (LLP)",
                                "Limited Liability Partnership (LLP)",
                            ),
                            ("Cooperative Society/Trust", "Cooperative Society/Trust"),
                        ],
                        max_length=50,
                    ),
                ),
                ("registered_address", models.TextField(blank=True)),
                ("state", models.CharField(blank=True, max_length=100)),
                ("district", models.CharField(blank=True, max_length=100)),
                ("pin_code", models.CharField(blank=True, max_length=6)),
                ("website", models.URLField(blank=True, null=True)),
                ("pan_no", models.CharField(blank=True, max_length=10)),
                ("tin", models.CharField(blank=True, max_length=20)),
                ("cin", models.CharField(blank=True, max_length=21)),
                (
                    "authorized_person_name",
                    models.CharField(blank=True, max_length=200),
                ),
                (
                    "authorized_person_designation",
                    models.CharField(blank=True, max_length=200),
                ),
                (
                    "authorized_person_email",
                    models.EmailField(blank=True, max_length=254),
                ),
                (
                    "authorized_person_mobile",
                    models.CharField(blank=True, max_length=15),
                ),
                ("authorized_person_pan", models.CharField(blank=True, max_length=10)),
                ("username", models.CharField(blank=True, max_length=50)),
                ("password", models.CharField(blank=True, max_length=100)),
                ("password_history", models.TextField(default="[]")),
                ("first_login", models.IntegerField(default=0)),
                ("completed_step", models.CharField(default="", max_length=50)),
                ("status", models.IntegerField(default=0)),
                ("application_submitted", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_verified", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="RVSFRegistrationFee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("min_turnover", models.IntegerField(blank=True, null=True)),
                ("max_turnover", models.IntegerField(blank=True, null=True)),
                ("registration_fee", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="State",
            fields=[
                ("state_id", models.AutoField(primary_key=True, serialize=False)),
                ("state_name", models.CharField(max_length=255)),
                ("country_id", models.IntegerField()),
                ("state_url", models.TextField(null=True)),
                ("status", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "State",
                "verbose_name_plural": "States",
                "db_table": "tbl_state",
            },
        ),
        migrations.CreateModel(
            name="ActiveSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user_type",
                    models.CharField(
                        choices=[
                            ("admin", "Django Admin/User"),
                            ("user", "Registration user"),
                        ],
                        max_length=10,
                    ),
                ),
                ("user_id", models.PositiveIntegerField()),
                ("session_key", models.CharField(max_length=64, unique=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "unique_together": {("user_type", "user_id")},
            },
        ),
        migrations.CreateModel(
            name="ProducerDeclaration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "turnover_23_24",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                (
                    "turnover_24_25",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                ("undertaking_file", models.FileField(upload_to="undertakings/")),
                ("ca_certificate_23_24", models.FileField(upload_to="ca_certs/")),
                ("ca_certificate_24_25", models.FileField(upload_to="ca_certs/")),
                ("declaration", models.BooleanField(default=False)),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "producer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="declaration",
                        to="registration.producergeneraldetails",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ManufacturingFacilityDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("address", models.TextField()),
                ("state", models.CharField(blank=True, max_length=100)),
                ("gstin", models.CharField(max_length=15)),
                ("year_of_establishment", models.PositiveIntegerField()),
                (
                    "manufacturing_capacity",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "assembly_capacity",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("activity_types", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "manufacturer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="facilitiesdetails",
                        to="registration.manufacturingdetails",
                    ),
                ),
                (
                    "producer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="manyfacturingfacilities",
                        to="registration.producergeneraldetails",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="manufacturingdetails",
            name="producer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="facilities",
                to="registration.producergeneraldetails",
            ),
        ),
        migrations.CreateModel(
            name="ProducerSalesData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("transport", "Transport"),
                            ("non_transport", "Non-Transport"),
                        ],
                        max_length=20,
                    ),
                ),
                ("financial_year", models.CharField(max_length=9)),
                (
                    "vehicle_type",
                    models.CharField(
                        choices=[
                            ("2W", "2 Wheeler"),
                            ("3W", "3 Wheeler"),
                            ("LMV", "Light Motor Vehicle"),
                            ("MMV", "Medium Motor Vehicle"),
                            ("HMV", "Heavy Motor Vehicle"),
                            ("Other", "Other"),
                        ],
                        max_length=10,
                    ),
                ),
                ("no_of_vehicles_manufactured", models.PositiveIntegerField(default=0)),
                ("no_of_vehicles_imported", models.PositiveIntegerField(default=0)),
                (
                    "no_of_vehicles_procurred_domestically",
                    models.PositiveIntegerField(default=0),
                ),
                ("open_market_vehicles", models.PositiveIntegerField(default=0)),
                (
                    "open_market_vehicle_weight",
                    models.DecimalField(decimal_places=4, default=0, max_digits=10),
                ),
                (
                    "open_market_steel_weight",
                    models.DecimalField(decimal_places=4, default=0, max_digits=10),
                ),
                (
                    "open_market_brand_name",
                    models.CharField(blank=True, max_length=100),
                ),
                ("producer_vehicles", models.PositiveIntegerField(default=0)),
                (
                    "producer_vehicle_weight",
                    models.DecimalField(decimal_places=4, default=0, max_digits=10),
                ),
                (
                    "producer_steel_weight",
                    models.DecimalField(decimal_places=4, default=0, max_digits=10),
                ),
                (
                    "producer_sale_file",
                    models.FileField(
                        blank=True, null=True, upload_to="producer_sale_files/"
                    ),
                ),
                ("cobranded_vehicles", models.PositiveIntegerField(default=0)),
                (
                    "cobranded_vehicle_weight",
                    models.DecimalField(decimal_places=4, default=0, max_digits=10),
                ),
                (
                    "cobranded_steel_weight",
                    models.DecimalField(decimal_places=4, default=0, max_digits=10),
                ),
                ("cobranded_brand_name", models.CharField(blank=True, max_length=100)),
                (
                    "cobranded_partner_file",
                    models.FileField(
                        blank=True, null=True, upload_to="cobranded_partner_files/"
                    ),
                ),
                ("selfuse_vehicles", models.PositiveIntegerField(default=0)),
                (
                    "selfuse_vehicle_weight",
                    models.DecimalField(decimal_places=4, default=0, max_digits=10),
                ),
                (
                    "selfuse_steel_weight",
                    models.DecimalField(decimal_places=4, default=0, max_digits=10),
                ),
                ("export_vehicles", models.PositiveIntegerField(default=0)),
                (
                    "vehicle_number_qty",
                    models.DecimalField(decimal_places=4, default=0, max_digits=10),
                ),
                (
                    "vehicle_weight_qty",
                    models.DecimalField(decimal_places=4, default=0, max_digits=10),
                ),
                (
                    "epr_qty",
                    models.DecimalField(decimal_places=4, default=0, max_digits=10),
                ),
                (
                    "epr_target",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=15, null=True
                    ),
                ),
                (
                    "producer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vehicle_sales",
                        to="registration.producergeneraldetails",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OtherProducerExcelData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("producer_name", models.CharField(max_length=255)),
                ("address", models.TextField(blank=True, null=True)),
                ("gst", models.CharField(blank=True, max_length=50, null=True)),
                ("mobile_no", models.CharField(blank=True, max_length=20, null=True)),
                ("email_id", models.EmailField(blank=True, max_length=254, null=True)),
                (
                    "vehicle_category",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "vehicle_type",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "other_vehicle_type",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("hsn_code", models.CharField(blank=True, max_length=50, null=True)),
                ("no_of_vehicle_sold", models.IntegerField(blank=True, null=True)),
                ("total_weight_vehicles", models.FloatField(blank=True, null=True)),
                ("total_weight_steel_used", models.FloatField(blank=True, null=True)),
                (
                    "producer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="otherproducerexcel",
                        to="registration.producergeneraldetails",
                    ),
                ),
                (
                    "sales_data",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="otherproducerexcelsales",
                        to="registration.producersalesdata",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CobrandedExcelData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cobrand_partners_name", models.CharField(max_length=255)),
                ("address", models.TextField(blank=True, null=True)),
                ("gst", models.CharField(blank=True, max_length=50, null=True)),
                ("mobile_no", models.CharField(blank=True, max_length=20, null=True)),
                ("email_id", models.EmailField(blank=True, max_length=254, null=True)),
                ("cobrand_share_percentage", models.FloatField(blank=True, null=True)),
                (
                    "manufactured_facility",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "vehicle_category",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "vehicle_type",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "other_vehicle_type",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("hsn_code", models.CharField(blank=True, max_length=50, null=True)),
                ("no_of_vehicle_sold", models.IntegerField(blank=True, null=True)),
                ("total_weight_vehicles", models.FloatField(blank=True, null=True)),
                ("total_weight_steel_used", models.FloatField(blank=True, null=True)),
                (
                    "producer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cobrandedexcel",
                        to="registration.producergeneraldetails",
                    ),
                ),
                (
                    "sales_data",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cobrandedexcelsales",
                        to="registration.producersalesdata",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="District",
            fields=[
                ("city_id", models.AutoField(primary_key=True, serialize=False)),
                ("city_name", models.CharField(max_length=255)),
                (
                    "state",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="districts",
                        to="registration.state",
                    ),
                ),
            ],
            options={
                "verbose_name": "District",
                "verbose_name_plural": "Districts",
                "db_table": "cities",
            },
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order_id", models.CharField(max_length=30, unique=True)),
                ("txn_id", models.CharField(blank=True, max_length=50, null=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("amount_initiated", models.IntegerField()),
                ("was_success", models.BooleanField(default=False)),
                ("status", models.CharField(blank=True, max_length=30, null=True)),
                ("log", models.TextField(blank=True, null=True)),
                ("registered_for", models.TextField(blank=True, null=True)),
                (
                    "txn_date",
                    models.DateTimeField(blank=True, default=django.utils.timezone.now),
                ),
                ("ru_date", models.DateTimeField(blank=True, null=True)),
                ("s2s_date", models.DateTimeField(blank=True, null=True)),
                (
                    "owner",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="registration.producergeneraldetails",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProducerSalesSummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("transport", "Transport"),
                            ("non_transport", "Non-Transport"),
                        ],
                        max_length=20,
                    ),
                ),
                ("financial_year", models.CharField(max_length=9)),
                (
                    "total_epr_target",
                    models.DecimalField(decimal_places=4, default=0, max_digits=10),
                ),
                ("ca_certificate", models.FileField(upload_to="ca_certificates/")),
                (
                    "producer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sales_summaries",
                        to="registration.producergeneraldetails",
                    ),
                ),
            ],
            options={
                "unique_together": {("producer", "category", "financial_year")},
            },
        ),
    ]
