# Generated by Django 5.2.6 on 2025-11-25 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_transaction_additional_registration_fee_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='transaction',
            table=None,
        ),
    ]
