# Generated by Django 5.2.6 on 2025-12-22 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_alter_transaction_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='transaction',
            table='registration_transaction',
        ),
    ]
