# Generated by Django 5.1.3 on 2025-07-22 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StateUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, null=True, unique=True)),
                ('password', models.CharField(blank=True, max_length=128, null=True)),
                ('auth_mobile', models.CharField(default=9999999999, max_length=10)),
                ('auth_email', models.EmailField(default='test@gmail.com', max_length=254)),
                ('OfficerName', models.CharField(max_length=100, null=True)),
                ('officerDesignation', models.CharField(max_length=100, null=True)),
                ('RoleAccess', models.CharField(max_length=100, null=True)),
                ('State_id', models.IntegerField(default=0)),
                ('District_id', models.IntegerField(default=0)),
                ('DisableStatus', models.IntegerField(default=0)),
            ],
        ),
    ]
