# Generated by Django 5.1.3 on 2025-07-28 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SpcbApp', '0002_stateroles'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationTrail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AppNo', models.CharField(max_length=100, null=True)),
                ('stateid', models.IntegerField(default=0)),
                ('designation', models.CharField(max_length=50, null=True)),
                ('marked_to_role', models.IntegerField(default=0)),
                ('marked_by_role', models.IntegerField(default=0)),
                ('comment', models.TextField(blank=True, null=True)),
                ('added_by_userid', models.IntegerField(default=0)),
                ('added_by_person', models.CharField(max_length=100, null=True)),
                ('added_to_userid', models.IntegerField(default=0)),
                ('added_to_person', models.CharField(max_length=100, null=True)),
                ('industry_user_id', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
