# Generated by Django 5.1.3 on 2025-07-29 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SpcbApp', '0003_applicationtrail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applicationtrail',
            old_name='designation',
            new_name='marked_by_designation',
        ),
        migrations.AddField(
            model_name='applicationtrail',
            name='marked_to_designation',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
