# Generated by Django 5.1.3 on 2025-07-29 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SpcbApp', '0004_rename_designation_applicationtrail_marked_by_designation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationtrail',
            name='marked_by_name',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='applicationtrail',
            name='marked_to_name',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
