# Generated by Django 5.1.3 on 2025-07-29 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SpcbApp', '0005_applicationtrail_marked_by_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicationtrail',
            name='marked_by_name',
        ),
        migrations.RemoveField(
            model_name='applicationtrail',
            name='marked_to_name',
        ),
    ]
