# Generated by Django 5.1.3 on 2025-07-29 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SpcbApp', '0006_remove_applicationtrail_marked_by_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AppStatus', models.IntegerField(unique=True)),
                ('Description', models.CharField(max_length=100)),
                ('DisableStatus', models.IntegerField(default=0)),
            ],
        ),
    ]
