# Generated by Django 5.1.3 on 2025-07-29 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SpcbApp', '0007_applicationstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationstatus',
            name='RoleAccess',
            field=models.IntegerField(default=0),
        ),
    ]
