# Generated by Django 5.1.3 on 2025-08-01 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SpcbApp', '0008_applicationstatus_roleaccess'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignupChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('industryid', models.IntegerField(default=0)),
                ('AppNo', models.IntegerField(default=0)),
                ('name_address', models.CharField(max_length=50, null=True)),
                ('remarks_name_address', models.CharField(max_length=500, null=True)),
                ('company_email', models.CharField(max_length=50, null=True)),
                ('remarks_company_email', models.CharField(max_length=500, null=True)),
                ('gst_certificate', models.CharField(max_length=50, null=True)),
                ('remarks_gst_certificate', models.CharField(max_length=500, null=True)),
                ('company_pan_card', models.CharField(max_length=50, null=True)),
                ('remarks_company_pan_card', models.CharField(max_length=500, null=True)),
                ('company_tin', models.CharField(max_length=50, null=True)),
                ('remarks_company_tin', models.CharField(max_length=500, null=True)),
                ('company_cin', models.CharField(max_length=50, null=True)),
                ('remarks_company_cin', models.CharField(max_length=500, null=True)),
                ('company_iec', models.CharField(max_length=50, null=True)),
                ('remarks_company_iec', models.CharField(max_length=500, null=True)),
                ('auth_person_details', models.CharField(max_length=500, null=True)),
                ('remarks_auth_person_details', models.CharField(max_length=500, null=True)),
                ('added_by', models.IntegerField(default=0)),
            ],
        ),
    ]
