# Generated by Django 5.1.3 on 2025-08-02 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SpcbApp', '0009_signupchecklist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signupchecklist',
            name='AppNo',
            field=models.CharField(max_length=30),
        ),
    ]
