# Generated by Django 5.1.3 on 2025-08-02 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SpcbApp', '0010_alter_signupchecklist_appno'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AppNo', models.CharField(max_length=100, unique=True)),
                ('Industry', models.IntegerField(default=0)),
                ('rvsf_address', models.TextField(blank=True, null=True)),
                ('remarks_rvsf_address', models.TextField(blank=True, null=True)),
                ('gps_location', models.CharField(blank=True, max_length=255, null=True)),
                ('remarks_gps_location', models.TextField(blank=True, null=True)),
                ('rvsf_state', models.CharField(blank=True, max_length=100, null=True)),
                ('remarks_rvsf_state', models.TextField(blank=True, null=True)),
                ('cto_certificate', models.CharField(blank=True, max_length=255, null=True)),
                ('remarks_cto_certificate', models.TextField(blank=True, null=True)),
                ('cto_validity', models.CharField(blank=True, max_length=100, null=True)),
                ('remarks_cto_validity', models.TextField(blank=True, null=True)),
                ('howm_certificate', models.CharField(blank=True, max_length=255, null=True)),
                ('remarks_howm_certificate', models.TextField(blank=True, null=True)),
                ('dic_certificate', models.CharField(blank=True, max_length=255, null=True)),
                ('remarks_dic_certificate', models.TextField(blank=True, null=True)),
                ('rvsf_certificate', models.CharField(blank=True, max_length=255, null=True)),
                ('remarks_rvsf_certificate', models.TextField(blank=True, null=True)),
                ('rvsf_certificate_validity', models.CharField(blank=True, max_length=100, null=True)),
                ('remarks_rvsf_certificate_validity', models.TextField(blank=True, null=True)),
                ('process_flow', models.TextField(blank=True, null=True)),
                ('remarks_process_flow', models.TextField(blank=True, null=True)),
                ('material_balance_sheet', models.TextField(blank=True, null=True)),
                ('remarks_material_balance_sheet', models.TextField(blank=True, null=True)),
                ('annual_return', models.TextField(blank=True, null=True)),
                ('remarks_annual_return', models.TextField(blank=True, null=True)),
                ('added_by', models.IntegerField(default=0)),
            ],
        ),
    ]
