# Generated by Django 5.1.3 on 2025-08-02 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SpcbApp', '0011_generalchecklist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='generalchecklist',
            old_name='Industry',
            new_name='Industryid',
        ),
    ]
