# Generated by Django 5.1.3 on 2025-08-03 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SpcbApp', '0012_rename_industry_generalchecklist_industryid'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('industryid', models.IntegerField()),
                ('AppNo', models.CharField(max_length=100, unique=True)),
                ('dismantling_equipment', models.BooleanField(default=False)),
                ('remarks_dismantling_equipment', models.TextField(blank=True, null=True)),
                ('depollution_equipment', models.BooleanField(default=False)),
                ('remarks_depollution_equipment', models.TextField(blank=True, null=True)),
                ('bailing_equipment', models.BooleanField(default=False)),
                ('remarks_bailing_equipment', models.TextField(blank=True, null=True)),
                ('shredding_equipment', models.BooleanField(default=False)),
                ('remarks_shredding_equipment', models.TextField(blank=True, null=True)),
                ('storage_equipment', models.BooleanField(default=False)),
                ('remarks_storage_equipment', models.TextField(blank=True, null=True)),
                ('classifier_equipment', models.BooleanField(default=False)),
                ('remarks_classifier_equipment', models.TextField(blank=True, null=True)),
                ('other_equipment', models.BooleanField(default=False)),
                ('remarks_other_equipment', models.TextField(blank=True, null=True)),
                ('added_by', models.IntegerField(default=0)),
                ('added_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
