# Generated by Django 5.1.3 on 2025-08-03 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SpcbApp', '0013_equipmentchecklist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmentchecklist',
            name='industryid',
            field=models.IntegerField(default=0),
        ),
    ]
