# Generated by Django 5.1.3 on 2025-08-03 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SpcbApp', '0014_alter_equipmentchecklist_industryid'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacilityChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('industryid', models.IntegerField(default=0)),
                ('AppNo', models.CharField(max_length=100, unique=True)),
                ('geo_tagged_video', models.BooleanField(default=False)),
                ('remarks_geo_tagged_video', models.TextField(blank=True, null=True)),
                ('total_rvsf_area', models.BooleanField(default=False)),
                ('remarks_total_rvsf_area', models.TextField(blank=True, null=True)),
                ('shift_number', models.BooleanField(default=False)),
                ('remarks_shift_number', models.TextField(blank=True, null=True)),
                ('employees_number', models.BooleanField(default=False)),
                ('remarks_employees_number', models.TextField(blank=True, null=True)),
                ('added_by', models.IntegerField(default=0)),
            ],
        ),
    ]
