# Generated by Django 5.1.3 on 2025-08-03 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SpcbApp', '0015_facilitychecklist'),
    ]

    operations = [
        migrations.CreateModel(
            name='CapacityChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('industryid', models.IntegerField(default=0)),
                ('AppNo', models.CharField(max_length=100, unique=True)),
                ('vehicle_category', models.BooleanField(default=False)),
                ('remarks_vehicle_category', models.TextField(blank=True, null=True)),
                ('vehicle_installed_capacity', models.BooleanField(default=False)),
                ('remarks_vehicle_installed_capacity', models.TextField(blank=True, null=True)),
                ('steel_installed_capacity', models.BooleanField(default=False)),
                ('remarks_steel_installed_capacity', models.TextField(blank=True, null=True)),
                ('vehicle_operating_capacity', models.BooleanField(default=False)),
                ('remarks_vehicle_operating_capacity', models.TextField(blank=True, null=True)),
                ('steel_operating_capacity', models.BooleanField(default=False)),
                ('remarks_steel_operating_capacity', models.TextField(blank=True, null=True)),
                ('added_by', models.IntegerField(default=0)),
            ],
        ),
    ]
