# Generated by Django 5.1.3 on 2025-08-03 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SpcbApp', '0016_capacitychecklist'),
    ]

    operations = [
        migrations.CreateModel(
            name='PollutionChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('industryid', models.IntegerField(default=0)),
                ('AppNo', models.CharField(max_length=100, unique=True)),
                ('air_pollution', models.BooleanField(default=False)),
                ('remarks_air_pollution', models.TextField(blank=True, null=True)),
                ('water_pollution', models.BooleanField(default=False)),
                ('remarks_water_pollution', models.TextField(blank=True, null=True)),
                ('noise_pollution', models.BooleanField(default=False)),
                ('remarks_noise_pollution', models.TextField(blank=True, null=True)),
                ('added_by', models.IntegerField(default=0)),
            ],
        ),
    ]
