# Generated by Django 5.1.3 on 2025-08-03 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SpcbApp', '0017_pollutionchecklist'),
    ]

    operations = [
        migrations.CreateModel(
            name='WasteRecycleChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('industryid', models.IntegerField(default=0)),
                ('AppNo', models.CharField(max_length=100, unique=True)),
                ('used_oil', models.BooleanField(default=False)),
                ('remarks_used_oil', models.TextField(blank=True, null=True)),
                ('plastic_waste', models.BooleanField(default=False)),
                ('remarks_plastic_waste', models.TextField(blank=True, null=True)),
                ('battery_waste', models.BooleanField(default=False)),
                ('remarks_battery_waste', models.TextField(blank=True, null=True)),
                ('tyre_waste', models.BooleanField(default=False)),
                ('remarks_tyre_waste', models.TextField(blank=True, null=True)),
                ('e_waste', models.BooleanField(default=False)),
                ('remarks_e_waste', models.TextField(blank=True, null=True)),
                ('steel_scrap', models.BooleanField(default=False)),
                ('remarks_steel_scrap', models.TextField(blank=True, null=True)),
                ('added_by', models.IntegerField(default=0)),
            ],
        ),
    ]
