# Generated by Django 5.1.3 on 2025-08-03 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SpcbApp', '0018_wasterecyclechecklist'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('industryid', models.IntegerField(default=0)),
                ('AppNo', models.CharField(max_length=100, unique=True)),
                ('declaration', models.BooleanField(default=False)),
                ('remarks_declaration', models.TextField(blank=True, null=True)),
                ('registration_fee_details', models.BooleanField(default=False)),
                ('remarks_registration_fee_details', models.TextField(blank=True, null=True)),
                ('added_by', models.IntegerField(default=0)),
            ],
        ),
    ]
