# Generated by Django 5.1.3 on 2025-08-05 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SpcbApp', '0019_paymentchecklist'),
    ]

    operations = [
        migrations.CreateModel(
            name='UntTrails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('industryid', models.IntegerField(default=0)),
                ('AppNo', models.CharField(max_length=100, unique=True)),
                ('stateid', models.IntegerField(default=0)),
                ('officerid', models.IntegerField(default=0)),
                ('SPCBComments', models.TextField(null=True)),
                ('UnitComments', models.TextField(null=True)),
                ('EditMode', models.IntegerField(default=0)),
                ('SPCBCommentDate', models.DateTimeField(blank=True, null=True)),
                ('UnitCommentDate', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
