# Generated by Django 5.1.3 on 2025-08-06 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SpcbApp', '0020_unttrails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unttrails',
            name='AppNo',
            field=models.CharField(max_length=100),
        ),
    ]
