# Generated by Django 5.1.2 on 2025-08-21 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SpcbApp', '0021_alter_unttrails_appno'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='stateroles',
            table='spcbapp_stateroles',
        ),
        migrations.AlterModelTable(
            name='stateusers',
            table='spcbapp_stateusers',
        ),
    ]
