# Generated by Django 5.2.6 on 2025-11-11 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SpcbApp', '0022_alter_stateroles_table_alter_stateusers_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='facilitychecklist',
            name='remarks_sectioned_power',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='facilitychecklist',
            name='sectioned_power',
            field=models.BooleanField(default=False),
        ),
    ]
