# Generated by Django 5.2.6 on 2025-11-19 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SpcbApp', '0023_facilitychecklist_remarks_sectioned_power_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationtrail',
            name='marked_by_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='applicationtrail',
            name='marked_to_id',
            field=models.IntegerField(default=0),
        ),
    ]
