# Generated by Django 5.2.6 on 2025-11-19 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SpcbApp', '0024_applicationtrail_marked_by_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicationtrail',
            name='marked_by_id',
        ),
        migrations.RemoveField(
            model_name='applicationtrail',
            name='marked_to_id',
        ),
    ]
