# Generated by Django 5.2.6 on 2025-12-26 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SpcbApp', '0025_remove_applicationtrail_marked_by_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stateusers',
            name='first_login',
            field=models.IntegerField(default=0),
        ),
    ]
