# Generated by Django 5.2.6 on 2025-12-30 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SpcbApp', '0026_stateusers_first_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('admin', 'Django Admin/User'), ('user', 'Registration user')], max_length=10)),
                ('user_id', models.PositiveIntegerField()),
                ('session_key', models.CharField(max_length=64, unique=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'unique_together': {('user_type', 'user_id')},
            },
        ),
    ]
