# Generated by Django 5.2.6 on 2026-01-12 05:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SpcbApp', '0027_activesession'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stateusers',
            name='first_login',
        ),
        migrations.AlterField(
            model_name='applicationtrail',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
