# Generated by Django 5.2.6 on 2026-01-12 06:26

import SpcbApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SpcbApp', '0028_remove_stateusers_first_login_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationtrail',
            name='created_at',
            field=models.DateTimeField(default=SpcbApp.models.get_india_time),
        ),
    ]
