# Generated by Django 5.2.6 on 2026-01-27 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SpcbApp', '0029_alter_applicationtrail_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='stateusers',
            name='first_login',
            field=models.IntegerField(default=0),
        ),
    ]
