# Generated by Django 5.2.6 on 2026-03-02 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SpcbApp', '0030_stateusers_first_login'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stateusers',
            old_name='DisableStatus',
            new_name='DisableStatus1',
        ),
    ]
