# Generated by Django 5.2.6 on 2026-04-22 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SpcbApp', '0032_rename_disablestatus1_stateusers_disablestatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='stateusers',
            name='password_history',
            field=models.TextField(default='[]'),
        ),
    ]
