# Generated by Django 5.2.6 on 2026-03-20 12:10

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('RvsfApp', '0063_rvsfdetails_gpcbid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'Transfer_Certificate_Category',
            },
        ),
        migrations.CreateModel(
            name='CertificateTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('producer_id', models.IntegerField()),
                ('rvsf_id', models.IntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DenominatedCertificate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rvsf_id', models.IntegerField()),
                ('total_certificate_value_denominated', models.DecimalField(decimal_places=3, max_digits=10)),
                ('denomination_date', models.DateTimeField(auto_now_add=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('financial_year', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='SteelScrapSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rvsf_id', models.IntegerField(db_index=True)),
                ('sale_date', models.DateField(default=django.utils.timezone.now)),
                ('buyer_type', models.CharField(max_length=100)),
                ('buyer_name', models.CharField(max_length=255)),
                ('buyer_address', models.TextField()),
                ('gst_number', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Enter a valid 15-character GST number', regex='^[0-9]{2}[A-Z]{5}[0-9]{4}[A-Z]{1}[1-9A-Z]{1}Z[0-9A-Z]{1}$')])),
                ('email', models.EmailField(max_length=254)),
                ('quantity_sold', models.DecimalField(decimal_places=3, max_digits=10)),
                ('invoice_amount', models.DecimalField(decimal_places=3, max_digits=10)),
                ('invoice_number', models.CharField(max_length=100)),
                ('invoice_pdf', models.FileField(upload_to='steel_scrap_invoices/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('financial_year', models.CharField(max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Transfer_Certificate_steel_scrap_sale',
                'ordering': ['-sale_date'],
            },
        ),
        migrations.CreateModel(
            name='WasteProcessing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rvsf_id', models.IntegerField(db_index=True)),
                ('waste_type', models.CharField(help_text='Fetched dynamically from OtherScrap', max_length=100)),
                ('activity', models.CharField(choices=[('recycled', 'Recycled'), ('refurbish', 'Refurbish'), ('disposal', 'Disposal')], max_length=20)),
                ('agreement_tsdf_certificate', models.FileField(blank=True, help_text='Agreement copy or TSDF membership certificate', null=True, upload_to='waste_tsdf_certificates/')),
                ('manifest_document', models.FileField(blank=True, null=True, upload_to='waste_manifest/')),
                ('processed_qty', models.DecimalField(decimal_places=3, max_digits=10)),
                ('buyer_name', models.CharField(max_length=255)),
                ('gst_number', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Enter a valid 15-character GST number', regex='^[0-9]{2}[A-Z]{5}[0-9]{4}[A-Z]{1}[1-9A-Z]{1}Z[0-9A-Z]{1}$')])),
                ('buyer_address', models.TextField(blank=True, null=True)),
                ('buyer_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('sale_date', models.DateField()),
                ('invoice_number', models.CharField(max_length=100)),
                ('invoice', models.FileField(upload_to='waste_invoice/')),
                ('financial_year', models.CharField(max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Transfer_Certificate_waste_processing',
            },
        ),
        migrations.CreateModel(
            name='DenominationDetail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rvsf_id', models.IntegerField()),
                ('denomination_kg', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('unique_id', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(choices=[('generated', 'Generated'), ('under_transfer', 'Under Transfer'), ('transferred', 'Transferred'), ('reverted', 'reverted')], default='generated', max_length=20)),
                ('denomination_master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='denomination_details', to='Transfer_Certificate.denominatedcertificate')),
            ],
        ),
        migrations.CreateModel(
            name='CertificateTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='pending', max_length=20)),
                ('transfer_date', models.DateField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='Transfer_Certificate.certificatetransaction')),
                ('denomination_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='Transfer_Certificate.denominationdetail')),
            ],
        ),
        migrations.CreateModel(
            name='FinancialYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('financial_year', models.CharField(max_length=12)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rvsf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RvsfApp.rvsfregistration')),
            ],
            options={
                'db_table': 'Transfer_Certificate_FY',
                'unique_together': {('rvsf', 'financial_year')},
            },
        ),
        migrations.CreateModel(
            name='ProcurementData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('financial_year', models.CharField(max_length=12)),
                ('procurement_date', models.DateField()),
                ('procurement_type', models.CharField(choices=[('ELV', 'Source of ELV'), ('AUTOMOBILE', 'Automobile Steel Scrap')], max_length=10)),
                ('collection_type', models.CharField(choices=[('collection_centre', 'Collection Centre'), ('bulk_consumer', 'Bulk Consumer'), ('owner_elv', 'Owner of ELV'), ('insurance_company', 'Insurance Company'), ('producer', 'Producer')], max_length=50)),
                ('source_name', models.CharField(blank=True, max_length=200, null=True)),
                ('gst_number', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('is_registered', models.BooleanField(blank=True, null=True)),
                ('vehicle_type', models.CharField(blank=True, max_length=50, null=True)),
                ('fuel_type', models.CharField(blank=True, max_length=50, null=True)),
                ('number_of_elvs', models.IntegerField(blank=True, null=True)),
                ('certificate_of_deposit', models.FileField(blank=True, null=True, upload_to='procurement/certificates/')),
                ('invoice_number', models.CharField(blank=True, max_length=100, null=True)),
                ('invoice_file', models.FileField(blank=True, null=True, upload_to='procurement/invoices/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rvsf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RvsfApp.rvsfregistration')),
            ],
        ),
        migrations.CreateModel(
            name='ProductionForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scrapping_date', models.DateField()),
                ('elv_type', models.CharField(blank=True, max_length=50, null=True)),
                ('scrapped_qty', models.PositiveIntegerField(blank=True, null=True)),
                ('scrapped_weight', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('automobile_scrap_processed', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('steel_scrap_recovered', models.DecimalField(decimal_places=3, max_digits=10)),
                ('other_scrap_recovered', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=10, null=True)),
                ('cert_generating_potential', models.DecimalField(decimal_places=3, max_digits=10)),
                ('financial_year', models.CharField(max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_entries', to='Transfer_Certificate.category')),
                ('rvsf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RvsfApp.rvsfregistration')),
            ],
            options={
                'db_table': 'Transfer_Certificate_ProductionForm',
            },
        ),
        migrations.CreateModel(
            name='OtherScrap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wasteType', models.CharField(max_length=100)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=10)),
                ('financial_year', models.CharField(max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rvsf', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='RvsfApp.rvsfregistration')),
                ('production', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='other_scraps', to='Transfer_Certificate.productionform')),
            ],
        ),
        migrations.CreateModel(
            name='OpeningBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('elv_type', models.CharField(max_length=50)),
                ('opening_balance_quantity', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('financial_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Transfer_Certificate.financialyear')),
            ],
            options={
                'db_table': 'Transfer_Certificate_openingbalance',
                'unique_together': {('financial_year', 'elv_type')},
            },
        ),
    ]
