# Generated by Django 5.1.3 on 2025-07-12 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RvsfApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rvsfregistration',
            name='iec',
        ),
        migrations.AddField(
            model_name='rvsfregistration',
            name='password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='rvsfregistration',
            name='username',
            field=models.CharField(max_length=150, null=True, unique=True),
        ),
    ]
