# Generated by Django 5.1.3 on 2025-07-12 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RvsfApp', '0003_rvsfregistration_auth_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rvsfregistration',
            name='auth_pan',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='rvsfregistration',
            name='auth_email',
            field=models.EmailField(default='test@gmail.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='rvsfregistration',
            name='auth_mobile',
            field=models.CharField(default=9999999999, max_length=10),
        ),
    ]
