# Generated by Django 5.1.3 on 2025-07-12 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RvsfApp', '0004_rvsfregistration_auth_pan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rvsfregistration',
            name='iec',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
