# Generated by Django 5.1.3 on 2025-07-15 10:54

import RvsfApp.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RvsfApp', '0007_equipmenttype_and_more'),
    ]

    operations = [
        
        migrations.CreateModel(
            name='EquipmentEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('geo_tagged_pdf', models.FileField(upload_to='RVSFDocs/equipmentspdf', validators=[RvsfApp.validators.validate_file_size])),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('equipment_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RvsfApp.equipmenttype')),
            ],
        ),
    ]
