# Generated by Django 5.1.3 on 2025-07-15 12:31

import RvsfApp.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RvsfApp', '0008_alter_generaldetails_annual_returns_pdf_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmententry',
            name='userid',
            field=models.IntegerField(default=0, unique=True),
        )
        
    ]
