# Generated by Django 5.1.3 on 2025-07-15 14:02

import RvsfApp.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RvsfApp', '0009_equipmententry_userid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmententry',
            name='equipment_type',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='generaldetails',
            name='annual_returns_pdf',
            field=models.FileField(upload_to='RVSFDocs/AnnualReturns/', validators=[RvsfApp.validators.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='generaldetails',
            name='cto_pdf',
            field=models.FileField(upload_to='RVSFDocs/Consent/', validators=[RvsfApp.validators.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='generaldetails',
            name='dic_pdf',
            field=models.FileField(upload_to='RVSFDocs/DICRegistration/', validators=[RvsfApp.validators.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='generaldetails',
            name='howm_pdf',
            field=models.FileField(upload_to='RVSFDocs/Authorization/', validators=[RvsfApp.validators.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='generaldetails',
            name='material_balance_pdf',
            field=models.FileField(upload_to='RVSFDocs/MaterialBalance/', validators=[RvsfApp.validators.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='generaldetails',
            name='process_flow_pdf',
            field=models.FileField(upload_to='RVSFDocs/FlowDaigram/', validators=[RvsfApp.validators.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='generaldetails',
            name='rvsf_pdf',
            field=models.FileField(upload_to='RVSFDocs/Rvsfpdf/', validators=[RvsfApp.validators.validate_file_size]),
        ),
    ]
