# Generated by Django 5.1.3 on 2025-07-15 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RvsfApp', '0011_alter_equipmententry_equipment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmententry',
            name='equipment_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='equipmententry',
            name='equipment_type',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
