# Generated by Django 5.1.3 on 2025-07-20 11:09

import RvsfApp.models
import RvsfApp.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RvsfApp', '0017_plantcapacity_vehicletype_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PollutionDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.IntegerField(default=0)),
                ('device_type', models.CharField(max_length=20, null=True)),
                ('name', models.CharField(max_length=200)),
                ('quantity', models.PositiveIntegerField()),
                ('device_doc', models.FileField(blank=True, null=True, upload_to=RvsfApp.models.DeviceDoc)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='WasteRecycled',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.IntegerField(default=0)),
                ('category', models.CharField(max_length=100)),
                ('qty_recovered', models.FloatField()),
                ('qty_recycled', models.FloatField()),
                ('recycler_name', models.CharField(max_length=255)),
                ('agreement_details', models.TextField()),
                ('agreement', models.FileField(blank=True, null=True, upload_to=RvsfApp.models.AgreementDoc)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        
    ]
