# Generated by Django 5.1.3 on 2025-07-21 11:15

import RvsfApp.models
import RvsfApp.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RvsfApp', '0019_confirmapplication_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='confirmapplication',
            name='paymentModeStatus',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='confirmapplication',
            name='paymentstatus',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='confirmapplication',
            name='transactionNo',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AlterField(
            model_name='confirmapplication',
            name='appno',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='confirmapplication',
            name='userid',
            field=models.IntegerField(default=0, unique=True),
        ),
        
    ]
