# Generated by Django 5.1.3 on 2025-07-22 01:10

import RvsfApp.models
import RvsfApp.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RvsfApp', '0020_confirmapplication_paymentmodestatus_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='confirmapplication',
            name='registrationfees',
            field=models.BigIntegerField(default=0),
        ),
        
    ]
