# Generated by Django 5.1.3 on 2025-07-22 12:37

import RvsfApp.models
import RvsfApp.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RvsfApp', '0021_confirmapplication_registrationfees_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmententry',
            name='geo_tagged_pdf',
            field=models.FileField(upload_to=RvsfApp.models.equipment_upload_path, validators=[RvsfApp.validators.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='generaldetails',
            name='annual_returns_pdf',
            field=models.FileField(upload_to=RvsfApp.models.annual_return_upload_path, validators=[RvsfApp.validators.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='generaldetails',
            name='cto_pdf',
            field=models.FileField(upload_to=RvsfApp.models.consent_upload_path, validators=[RvsfApp.validators.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='generaldetails',
            name='dic_pdf',
            field=models.FileField(upload_to=RvsfApp.models.dic_upload_path, validators=[RvsfApp.validators.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='generaldetails',
            name='howm_pdf',
            field=models.FileField(upload_to=RvsfApp.models.authorization_upload_path, validators=[RvsfApp.validators.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='generaldetails',
            name='material_balance_pdf',
            field=models.FileField(upload_to=RvsfApp.models.material_balance_upload_path, validators=[RvsfApp.validators.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='generaldetails',
            name='process_flow_pdf',
            field=models.FileField(upload_to=RvsfApp.models.flow_diagram_upload_path, validators=[RvsfApp.validators.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='generaldetails',
            name='rvsf_pdf',
            field=models.FileField(upload_to=RvsfApp.models.rvsf_upload_path, validators=[RvsfApp.validators.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='rvsffacility',
            name='geo_video',
            field=models.FileField(upload_to=RvsfApp.models.geo_video_upload_path, validators=[RvsfApp.validators.validate_file_size]),
        ),
    ]
