# Generated by Django 5.1.3 on 2025-07-28 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RvsfApp', '0023_confirmapplication_state_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='confirmapplication',
            name='role_id',
            field=models.IntegerField(default=0),
        ),
    ]
