# Generated by Django 5.1.3 on 2025-07-28 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RvsfApp', '0024_confirmapplication_role_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='confirmapplication',
            name='appstatus',
            field=models.IntegerField(choices=[(1, 'Submitted'), (2, 'Scrutiny'), (3, 'Accepted'), (4, 'Inspection'), (5, 'Approved'), (6, 'Clarification Required'), (7, 'Response Recieved'), (8, 'Rejected')], default=1),
        ),
    ]
