# Generated by Django 5.1.3 on 2025-07-28 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RvsfApp', '0025_confirmapplication_appstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confirmapplication',
            name='appstatus',
            field=models.IntegerField(choices=[(1, 'Submitted'), (2, 'Scrutiny'), (3, 'Inspection'), (4, 'Approved'), (5, 'Clarification Required'), (6, 'Response Recieved'), (7, 'Rejected')], default=1),
        ),
    ]
