# Generated by Django 5.1.3 on 2025-08-06 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RvsfApp', '0028_confirmapplication_editparta_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='confirmapplication',
            old_name='EditPartA',
            new_name='incomplete',
        ),
        migrations.RemoveField(
            model_name='confirmapplication',
            name='EditPartB',
        ),
        migrations.RemoveField(
            model_name='confirmapplication',
            name='EditPartC',
        ),
        migrations.RemoveField(
            model_name='confirmapplication',
            name='EditPartD',
        ),
    ]
