# Generated by Django 5.1.3 on 2025-09-09 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RvsfApp', '0034_rename_transaction_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='generaldetails',
            name='district',
            field=models.CharField(default='NA', max_length=100),
        ),
        migrations.AddField(
            model_name='generaldetails',
            name='pin_code',
            field=models.CharField(default='NA', max_length=20),
        ),
        migrations.AlterField(
            model_name='generaldetails',
            name='state',
            field=models.CharField(default='NA', max_length=100),
        ),
    ]
