# Generated by Django 5.1.3 on 2025-09-10 02:09

import RvsfApp.models
import RvsfApp.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RvsfApp', '0035_generaldetails_district_generaldetails_pin_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='generaldetails',
            name='cin_pdf',
            field=models.FileField(blank=True, upload_to=RvsfApp.models.CinDoc, validators=[RvsfApp.validators.validate_file_size]),
        ),
        migrations.AddField(
            model_name='generaldetails',
            name='gst_pdf',
            field=models.FileField(blank=True, upload_to=RvsfApp.models.GstDoc, validators=[RvsfApp.validators.validate_file_size]),
        ),
        migrations.AddField(
            model_name='generaldetails',
            name='iec_pdf',
            field=models.FileField(blank=True, upload_to=RvsfApp.models.IecDoc, validators=[RvsfApp.validators.validate_file_size]),
        ),
        migrations.AddField(
            model_name='generaldetails',
            name='pan_pdf',
            field=models.FileField(blank=True, upload_to=RvsfApp.models.PanDoc, validators=[RvsfApp.validators.validate_file_size]),
        ),
        migrations.AddField(
            model_name='generaldetails',
            name='tin_pdf',
            field=models.FileField(blank=True, upload_to=RvsfApp.models.TinDoc, validators=[RvsfApp.validators.validate_file_size]),
        ),
    ]
