# Generated by Django 5.2.6 on 2025-10-28 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RvsfApp', '0039_rvsfdetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generaldetails',
            name='address',
        ),
        migrations.RemoveField(
            model_name='generaldetails',
            name='annual_returns_pdf',
        ),
        migrations.RemoveField(
            model_name='generaldetails',
            name='consent_validity',
        ),
        migrations.RemoveField(
            model_name='generaldetails',
            name='cto_number',
        ),
        migrations.RemoveField(
            model_name='generaldetails',
            name='cto_pdf',
        ),
        migrations.RemoveField(
            model_name='generaldetails',
            name='dic_pdf',
        ),
        migrations.RemoveField(
            model_name='generaldetails',
            name='dic_validity',
        ),
        migrations.RemoveField(
            model_name='generaldetails',
            name='district',
        ),
        migrations.RemoveField(
            model_name='generaldetails',
            name='howm_pdf',
        ),
        migrations.RemoveField(
            model_name='generaldetails',
            name='howm_validity',
        ),
        migrations.RemoveField(
            model_name='generaldetails',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='generaldetails',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='generaldetails',
            name='material_balance_pdf',
        ),
        migrations.RemoveField(
            model_name='generaldetails',
            name='pin_code',
        ),
        migrations.RemoveField(
            model_name='generaldetails',
            name='process_flow_pdf',
        ),
        migrations.RemoveField(
            model_name='generaldetails',
            name='rvsf_pdf',
        ),
        migrations.RemoveField(
            model_name='generaldetails',
            name='rvsf_reg_no',
        ),
        migrations.RemoveField(
            model_name='generaldetails',
            name='rvsf_validity',
        ),
        migrations.RemoveField(
            model_name='generaldetails',
            name='state',
        ),
        migrations.RemoveField(
            model_name='rvsfdetails',
            name='cin_pdf',
        ),
        migrations.RemoveField(
            model_name='rvsfdetails',
            name='district',
        ),
        migrations.RemoveField(
            model_name='rvsfdetails',
            name='gst_pdf',
        ),
        migrations.RemoveField(
            model_name='rvsfdetails',
            name='iec_pdf',
        ),
        migrations.RemoveField(
            model_name='rvsfdetails',
            name='pan_pdf',
        ),
        migrations.RemoveField(
            model_name='rvsfdetails',
            name='pin_code',
        ),
        migrations.RemoveField(
            model_name='rvsfdetails',
            name='tin_pdf',
        ),
    ]
