# Generated by Django 5.2.6 on 2025-10-28 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RvsfApp', '0040_remove_generaldetails_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rvsfregistration',
            name='password_history',
            field=models.TextField(default='[]'),
        ),
        migrations.CreateModel(
            name='ActiveSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('admin', 'Django Admin/User'), ('user', 'Registration user')], max_length=10)),
                ('user_id', models.PositiveIntegerField()),
                ('session_key', models.CharField(max_length=64, unique=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'unique_together': {('user_type', 'user_id')},
            },
        ),
    ]
