# Generated by Django 5.2.6 on 2025-10-29 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RvsfApp', '0042_equipmententry_capacity_equipment_perton_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rvsffacility',
            name='sectioned_power',
            field=models.IntegerField(default=0),
        ),
    ]
