# Generated by Django 5.2.6 on 2025-10-31 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RvsfApp', '0043_rvsffacility_sectioned_power'),
    ]

    operations = [
        migrations.AddField(
            model_name='rvsfregistration',
            name='undertaking',
            field=models.FileField(blank=True, null=True, upload_to='RVSFDocs/undertaking/'),
        ),
    ]
