# Generated by Django 5.2.6 on 2025-10-31 10:20

import RvsfApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RvsfApp', '0044_rvsfregistration_undertaking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rvsfregistration',
            name='undertaking',
            field=models.FileField(blank=True, null=True, upload_to=RvsfApp.models.unique_undertaking_path),
        ),
    ]
