# Generated by Django 5.2.6 on 2025-11-12 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RvsfApp', '0045_alter_rvsfregistration_undertaking'),
    ]

    operations = [
        migrations.AddField(
            model_name='rvsfregistration',
            name='designation',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
