# Generated by Django 5.2.6 on 2025-11-27 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RvsfApp', '0049_paymentlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('initial', 'Initial Payment'), ('additional', 'Additional Payment')], default='initial', max_length=20),
        ),
        migrations.AlterModelTable(
            name='payment',
            table='payment',
        ),
    ]
