# Generated by Django 5.2.6 on 2025-12-08 10:06

import RvsfApp.models
import RvsfApp.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RvsfApp', '0053_equipmententry_status_generaldetails_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rvsfdetails',
            name='annual_returns_pdf1',
            field=models.FileField(default='', upload_to=RvsfApp.models.annual_return_upload_path1, validators=[RvsfApp.validators.validate_file_size]),
            preserve_default=False,
        ),
    ]
