# Generated by Django 5.2.6 on 2025-12-23 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RvsfApp', '0054_rvsfdetails_annual_returns_pdf1'),
    ]

    operations = [
        migrations.AddField(
            model_name='rvsfdetails',
            name='district',
            field=models.CharField(default='NA', max_length=100),
        ),
    ]
