# Generated by Django 5.2.6 on 2026-01-06 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RvsfApp', '0058_rvsfdetails_annual_returns_pdf2'),
    ]

    operations = [
        migrations.AddField(
            model_name='rvsffacility',
            name='storage_depolluted_fluids',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rvsffacility',
            name='storage_hazardous_waste',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rvsffacility',
            name='storage_others',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rvsffacility',
            name='storage_others_description',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rvsffacility',
            name='storage_parking_area',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rvsffacility',
            name='storage_processed_scrap',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rvsffacility',
            name='storage_segregated_spares',
            field=models.IntegerField(default=0),
        ),
    ]
