# Generated by Django 5.2.6 on 2026-01-12 10:39

import RvsfApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RvsfApp', '0059_rvsffacility_storage_depolluted_fluids_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rvsfregistration',
            name='attested_certificate',
            field=models.FileField(blank=True, null=True, upload_to=RvsfApp.models.attested_certificate_path),
        ),
        migrations.AddField(
            model_name='rvsfregistration',
            name='attested_certificate_uploaded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
