# Generated by Django 5.2.6 on 2026-01-23 10:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RvsfApp', '0061_confirmapplication_certificateno'),
    ]

    operations = [
        migrations.AddField(
            model_name='rvsfdetails',
            name='unit_commencement_year',
            field=models.CharField(blank=True, max_length=4, null=True, validators=[django.core.validators.RegexValidator(code='invalid_year', message='Year must be exactly 4 digits (e.g., 2022)', regex='^\\d{4}$')]),
        ),
    ]
