# Generated by Django 5.2.6 on 2026-03-30 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RvsfApp', '0063_rvsfdetails_gpcbid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmententry',
            name='equipment_description',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
