"""
Django settings for ELV project.

Generated by 'django-admin startproject' using Django 5.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
TEMPLATE_DIR = str(BASE_DIR / "registration" / "templates")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-xj!ebnm6qy7x5bf7wl0f(ls@=px3n*u@acbusd@2u=_#7_uenw'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'registration',
    'RvsfApp',
    'SpcbApp',
    'captcha',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'registration.middleware.AutoLogout',
    'registration.middleware.NoCacheMiddleware',
    'registration.middleware.RemoveServerHeadersMiddleware',
]

CSRF_TRUSTED_ORIGINS = ["https://demosignergateway.emsigner.com/"]

ROOT_URLCONF = 'ELV.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [TEMPLATE_DIR],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'ELV.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases


# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.mysql',
#         'NAME': 'elv_new_db',
#         'USER':'root',
#         'PASSWORD':'',
#         'HOST':'localhost',
#         'PORT':'3307',
#         'OPTIONS': {
#             'sql_mode': 'STRICT_TRANS_TABLES',
#         },
#     }
# }


# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.mysql',
#         'NAME': 'elv_08-07-2025',
#         'USER':'root',
#         'PASSWORD':'root',
#         'HOST':'localhost',
#         'PORT':'8889',
#         'OPTIONS': {
#             'sql_mode': 'STRICT_TRANS_TABLES',
#         },
#     }
# }


# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.mysql',
#         'NAME': 'elv_latest_23_06_2025',
#         'USER':'cpcbelv',
#         'PASSWORD':'ELVj3uD@cpcb',
#         'HOST':'localhost',
#         'PORT':'3306',
#         'OPTIONS': {
#             'sql_mode': 'STRICT_TRANS_TABLES',
#         },
#     }
# }

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'elv_new',
        'USER':'cpcbelv',
        'PASSWORD':'ELVj3uD@cpcb',
        'HOST':'10.24.84.232',
        'PORT':'3306',
        'OPTIONS': {
            'sql_mode': 'STRICT_TRANS_TABLES',
        },
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
 
MEDIA_URL = '/media/'
# MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_ROOT = '/opt/ELV/documents/'


# CAPTCHA_IMAGE_SIZE = (175, 50)  # Set the width and height of the CAPTCHA image
# CAPTCHA_LENGTH = 6  # Increase the number of characters in the CAPTCHA (default is 4)
# CAPTCHA_FONT_SIZE = 30  # Set the font size for the CAPTCHA text
# # CAPTCHA_FONT_PATH = "/path/to/font.ttf"  # Provide a specific path to a .ttf font file
# CAPTCHA_NOISE_FUNCTIONS = ('captcha.helpers.noise_arcs', 'captcha.helpers.noise_dots')
# CAPTCHA_BACKGROUND_COLOR = "#f0f2f5"  # Background color
# CAPTCHA_FOREGROUND_COLOR = "#020f2c"  # Text color
# CAPTCHA_CHALLENGE_FUNCT = 'captcha.helpers.random_char_challenge'  # Mix of letters and numbers
# CAPTCHA_TIMEOUT = 5  # Timeout for CAPTCHA in minutes (default is 5)
# CAPTCHA_FONT_PATH = None  # Use default font or specify a path to a .ttf file


CAPTCHA_IMAGE_SIZE = (175, 50)  # Set the width and height of the CAPTCHA image
CAPTCHA_LENGTH = 6  # Increase the number of characters in the CAPTCHA (default is 4)
CAPTCHA_FONT_SIZE = 30  # Set the font size for the CAPTCHA text
# CAPTCHA_FONT_PATH = "/path/to/font.ttf"  # Provide a specific path to a .ttf font file
CAPTCHA_NOISE_FUNCTIONS = ('captcha.helpers.noise_arcs', 'captcha.helpers.noise_dots')
CAPTCHA_BACKGROUND_COLOR = "#f0f2f5"  # Background color
CAPTCHA_FOREGROUND_COLOR = "#020f2c"  # Text color
# CAPTCHA_CHALLENGE_FUNCT = 'captcha.helpers.random_char_challenge'  # Mix of letters and numbers
CAPTCHA_CHALLENGE_FUNCT = 'registration.captcha_challenges.complex_symbol_challenge'

CAPTCHA_TIMEOUT = 5  # Timeout for CAPTCHA in minutes (default is 5)
# CAPTCHA_FONT_PATH = None  # Use default font or specify a path to a .ttf file

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field



# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_HOST = 'smtp.gmail.com'  # Change if using another provider
# EMAIL_PORT = 587
# EMAIL_USE_TLS = True
# EMAIL_HOST_USER = 'help.cpcb@gmail.com'  # Your email
# EMAIL_HOST_PASSWORD = 'qqogaurtygbeakdi'  # App password or actual password
# DEFAULT_FROM_EMAIL = EMAIL_HOST_USER

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'  # Change if using another provider
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'hwmd.cpcb@gmail.com'  # Your email
EMAIL_HOST_PASSWORD = "sntyeregrawgzrue"
# EMAIL_HOST_USER = 'test.consent.cpcb@gmail.com'  # Your email
# EMAIL_HOST_PASSWORD = 'lvznpwmaaiqhtqdg'  # App password or actual password:
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER


# SMS
# TWILIO_SID = 'ACc2434ce19dd33de8bfe4ac5413d1f234'
# TWILIO_AUTH_TOKEN = 'da97df03da87317c75e08d516ac3995a'
# TWILIO_PHONE_NUMBER = '+18483152997'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
AUTH_USER_MODEL = 'registration.User'

MEDIA_URL = '/documents/'
MEDIA_ROOT = BASE_DIR / 'documents'




# settings.py

BILLDESK_MERCHANT_ID = 'XBIHARGRAS'
BILLDESK_CLIENT_ID = 'xbihargras'
# BILLDESK_KEY_ID = 'wi1XhfQeOQQ5'  # <-- This is your Authorization key
BILLDESK_KEY_ID = '7VYad7hnhet13jXvxCFoFAvpAwTqH60I'  # <-- This is your Authorization key
BILLDESK_ENCRYPTION_KEY = 'zvSpVgG0hZO5pCcpjM0Em48IauHP8mqL'
BILLDESK_SIGNING_KEY = '21eWrxFIcloCBXOPKf65iscLd8PPKLMP'
BILLDESK_API_ENDPOINT = 'https://uat1.billdesk.com/u2/payments/ve1_2/orders/create'




# Set session to expire in 30 minutes (1800 seconds)
# SESSION_COOKIE_AGE = 1800  # 30 minutes

# Optional: Ensure the session is deleted when the browser is closed
# SESSION_EXPIRE_AT_BROWSER_CLOSE = True

LOGGING ={
    'version':1,
    'loggers':{
        'django':{
            'handlers':['console'],
            'level':'DEBUG',
        }
        },
    'handlers':{
        'console':{
            'level':'INFO',
            'class':'logging.StreamHandler',
            'formatter':'simpleRe',
        }
        },
    'formatters':{
        'simpleRe':{
            'format':'{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style':'{',
            
        }
    }
}


import warnings

warnings.filterwarnings(
    'ignore',
    message='Model .* was already registered',
    category=RuntimeWarning,
)
